version: "3.9"
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/data
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "V0lum3bu11@n"
      ACCEPT_EULA: "Y"
  web:
    build:
      context: ./RxSavingsSolutionsCodeChallenge
    ports:
      - 8080:80
    depends_on:
      - db
